import type { ResolvedSource } from './resolver.js'; import type { Source } from './schema.js';
export const MAX_JUMPER_VOICES = 32; export const ALLOWED_RATES = [0.5, 0.75, 1, 1.25, 1.5, 2] as const; export type AudioRate = typeof ALLOWED_RATES[number];
type Voice = { element: HTMLAudioElement; busy: boolean; cleanup: (() => void) | undefined };
export class MediaElementAudioEngine {
  private bases: Voice[] = []; private jumpers: Voice[] = []; private rate: AudioRate = 1;
  constructor(private readonly createElement: () => HTMLAudioElement = () => new Audio()) {}
  async authorize(baseCount: number): Promise<void> { if (this.bases.length || this.jumpers.length) return; const create = (): Voice => { const element = this.createElement(); element.preload = 'auto'; element.preservesPitch = false; (element as HTMLAudioElement & { webkitPreservesPitch?: boolean }).webkitPreservesPitch = false; return { element, busy: false, cleanup: undefined }; }; this.bases = Array.from({ length: baseCount }, create); this.jumpers = Array.from({ length: MAX_JUMPER_VOICES }, create); const silent = 'data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACABAAZGF0YQAAAAA='; const all = [...this.bases, ...this.jumpers]; await Promise.all(all.map(async (voice) => { voice.element.src = silent; await voice.element.play(); voice.element.pause(); })); }
  async startBase(index: number, source: Source, resolved: ResolvedSource, volume: number): Promise<void> { const voice = this.bases[index]; if (!voice) throw new Error('Unknown base slot'); await this.play(voice, source, resolved, volume, true); }
  async trigger(source: Source, resolved: ResolvedSource, volume: number): Promise<boolean> { const voice = this.jumpers.find((candidate) => !candidate.busy); if (!voice) return false; await this.play(voice, source, resolved, volume, false); return true; }
  async setRate(rate: AudioRate): Promise<void> { if (!ALLOWED_RATES.includes(rate)) throw new Error('Unsupported rate'); const previous = this.rate; const voices = [...this.bases, ...this.jumpers].filter((voice) => voice.busy); try { for (const voice of voices) { voice.element.playbackRate = rate; if (voice.element.playbackRate !== rate) throw new Error('Rate rejected'); } this.rate = rate; } catch (error) { for (const voice of voices) voice.element.playbackRate = previous; throw error; } }
  pause() { for (const voice of [...this.bases, ...this.jumpers]) if (voice.busy) voice.element.pause(); }
  async resume() { await Promise.all([...this.bases, ...this.jumpers].filter((voice) => voice.busy).map((voice) => voice.element.play())); }
  stop() { for (const voice of [...this.bases, ...this.jumpers]) { voice.cleanup?.(); voice.cleanup = undefined; voice.busy = false; voice.element.pause(); voice.element.removeAttribute('src'); voice.element.load(); } }
  private async play(voice: Voice, source: Source, resolved: ResolvedSource, volume: number, base: boolean) { voice.cleanup?.(); voice.busy = true; const start = source.clip?.start_seconds ?? 0; const end = source.clip?.end_seconds; const element = voice.element; element.src = resolved.url; element.volume = volume; element.playbackRate = this.rate; element.currentTime = start; const finish = () => { if (!base) { voice.busy = false; voice.cleanup?.(); } }; const monitor = () => { if (end !== undefined && element.currentTime >= end - 0.02) { if (base) { element.currentTime = start; void element.play(); } else finish(); } }; element.loop = base && end === undefined; element.addEventListener('timeupdate', monitor); element.addEventListener('ended', base ? () => { element.currentTime = start; void element.play(); } : finish, { once: !base }); voice.cleanup = () => { element.removeEventListener('timeupdate', monitor); resolved.release(); }; await element.play(); }
}
