import { type AudioRate, MediaElementAudioEngine } from './audio-engine.js'; import { type RuntimePolicy, type Scenario, type Source, hydrateCandidate } from './schema.js'; import { type Random, browserClock, JumperScheduler } from './scheduler.js'; import type { ResolvedSource, SourceResolverRegistry } from './resolver.js';
export type ApplicationState = 'LOADING' | 'READY' | 'PLAYING' | 'PAUSED' | 'STOPPING' | 'STOPPED' | 'ERROR'; export interface Snapshot { state: ApplicationState; scenario?: Scenario; rate: AudioRate; error?: string; }
export class ApplicationController { private state: ApplicationState = 'STOPPED'; private active: Scenario | undefined; private generation = 0; private abort: AbortController | undefined; private resolved = new Map<string, ResolvedSource>(); private scheduler: JumperScheduler | undefined; private rate: AudioRate = 1; private listeners = new Set<(snapshot: Snapshot) => void>();
  constructor(private readonly runtime: RuntimePolicy, private readonly resolvers: SourceResolverRegistry, private readonly engine: MediaElementAudioEngine, private readonly rng: Random = { next: () => crypto.getRandomValues(new Uint32Array(1))[0]! / 0x1_0000_0000 }) {}
  subscribe(listener: (snapshot: Snapshot) => void) { this.listeners.add(listener); listener(this.snapshot); return () => this.listeners.delete(listener); } get snapshot(): Snapshot { return Object.freeze(this.active ? { state: this.state, scenario: this.active, rate: this.rate } : { state: this.state, rate: this.rate }); } private publish(error?: string) { const snapshot: Snapshot = error === undefined ? this.snapshot : { ...this.snapshot, error }; for (const listener of this.listeners) listener(snapshot); }
  async load(candidate: Scenario): Promise<void> { this.generation += 1; const generation = this.generation; this.abort?.abort(); this.abort = new AbortController(); this.state = 'LOADING'; this.publish(); const unique = [...new Set([...candidate.bases.map((base) => base.source), ...candidate.jumpers.flatMap((jumper) => jumper.sources)].map((source) => source.location))]; try { for (const location of unique) { const source = [...candidate.bases.map((base) => base.source), ...candidate.jumpers.flatMap((jumper) => jumper.sources)].find((item) => item.location === location)!; this.resolved.set(location, await this.resolvers.resolve(source, this.runtime, { id: location, signal: this.abort.signal })); } await hydrateCandidate(candidate, async (source) => this.resolved.get(source.location)?.durationSeconds ?? NaN); if (generation !== this.generation) return; this.engine.stop(); this.active = candidate; this.state = 'READY'; this.publish(); } catch (error) { if (generation !== this.generation) return; this.release(); this.state = 'ERROR'; this.publish(error instanceof Error ? error.message : 'Loading failed'); throw error; } }
  async start(): Promise<void> { if (!this.active || this.state !== 'READY') return; await this.engine.authorize(this.active.bases.length); await Promise.all(this.active.bases.map((base, i) => this.engine.startBase(i, base.source, this.source(base.source), sample(base.source, this.rng)))); this.scheduler = new JumperScheduler(browserClock, (id) => { const jumper = this.active?.jumpers.find((item) => item.id === id); if (!jumper) return; const source = jumper.sources[Math.floor(this.rng.next() * jumper.sources.length)]!; void this.engine.trigger(source, this.source(source), sample(source, this.rng)); }); for (const jumper of this.active.jumpers) this.scheduler.add(jumper.id, jumper.schedule, this.rng); this.scheduler.start(); this.state = 'PLAYING'; this.publish(); }
  async togglePause(): Promise<void> { if (this.state === 'PLAYING') { this.engine.pause(); this.scheduler?.pause(); this.state = 'PAUSED'; } else if (this.state === 'PAUSED') { await this.engine.resume(); this.scheduler?.start(); this.state = 'PLAYING'; } this.publish(); }
  async setRate(rate: AudioRate) { await this.engine.setRate(rate); this.rate = rate; this.publish(); }
  stop() { this.generation += 1; this.abort?.abort(); this.state = 'STOPPING'; this.publish(); this.scheduler?.stop(); this.scheduler = undefined; this.engine.stop(); this.release(); this.active = undefined; this.state = 'STOPPED'; this.publish(); } async shutdown() { this.stop(); } private source(source: Source) { const resolved = this.resolved.get(source.location); if (!resolved) throw new Error('Unresolved source'); return resolved; } private release() { for (const source of this.resolved.values()) source.release(); this.resolved.clear(); } }
function sample(source: Source, rng: Random) { return source.volume.min + rng.next() * (source.volume.max - source.volume.min); }
