import { app, BrowserWindow, dialog, ipcMain, Menu, Tray, protocol, nativeImage, type IpcMainInvokeEvent } from 'electron'; import { parseScenario, type Scenario } from '@ambiental/core';
import { readFile, realpath, stat, writeFile } from 'node:fs/promises';
import { createReadStream } from 'node:fs';
import { basename, extname, join, normalize } from 'node:path';
import { DesktopProviderRegistry } from './providers.js';

const cli = process.argv.includes('--cli'); const providers = new DesktopProviderRegistry(); let windowRef: BrowserWindow | undefined; let tray: Tray | undefined; let quitting = false;
const defaultScenarioPath = app.isPackaged ? join(process.resourcesPath, 'default-scenario.json') : new URL('../../../packages/core/assets/default-scenario.json', import.meta.url);
let scenario: Scenario;
protocol.registerSchemesAsPrivileged([{ scheme: 'ambiental', privileges: { standard: true, secure: true, supportFetchAPI: true, stream: true } }]);
function bundleMime(path: string) { return extname(path) === '.js' ? 'text/javascript' : extname(path) === '.css' ? 'text/css' : extname(path) === '.html' ? 'text/html' : 'application/octet-stream'; }
function ensureWindow() {
  if (windowRef) return windowRef;
  windowRef = new BrowserWindow({ width: 1120, height: 760, show: !cli, webPreferences: { preload: new URL('./preload.cjs', import.meta.url).pathname, nodeIntegration: false, contextIsolation: true, sandbox: true, webSecurity: true, backgroundThrottling: false } });
  windowRef.webContents.on('will-navigate', (event) => event.preventDefault());
  windowRef.webContents.setWindowOpenHandler(() => ({ action: 'deny' }));
  windowRef.webContents.on('did-fail-load', (_event, code, description, url) => console.error(`Renderer failed to load ${url}: ${code} ${description}`));
  windowRef.webContents.on('render-process-gone', (_event, details) => console.error(`Renderer exited: ${details.reason}`));
  windowRef.on('close', (event) => { if (!quitting) { event.preventDefault(); windowRef?.hide(); } });
  void windowRef.loadURL('ambiental://bundle/index.html').catch((error: unknown) => console.error('Renderer navigation failed', error));
  return windowRef;
}
function assertTrustedSender(event: IpcMainInvokeEvent) { const current = windowRef; const url = new URL(event.sender.getURL()); if (!current || event.sender !== current.webContents || event.senderFrame !== current.webContents.mainFrame || url.protocol !== 'ambiental:' || url.hostname !== 'bundle') throw new Error('Untrusted IPC sender'); }
function rebuildTray() { tray?.destroy(); tray = new Tray(nativeImage.createEmpty()); tray.setToolTip(`Ambientalheehee — ${scenario.name}`); tray.setContextMenu(Menu.buildFromTemplate([{ label: 'Open', click: () => ensureWindow().show() }, { label: 'Hide', click: () => windowRef?.hide() }, { type: 'separator' }, { label: 'Quit', click: () => { quitting = true; app.quit(); } }])); }
function safeName(name: string) { const stem = name.replace(/[^A-Za-z0-9._-]+/g, '-').replace(/^-+|-+$/g, '').replace(/\.json$/i, '') || 'scenario'; return `${stem}.json`; }
function validatedDesktopSource(value: unknown) { return parseScenario(JSON.stringify({ version: 1, name: 'preview', bases: [{ id: 'preview', source: value }], jumpers: [] }), 'desktop').bases[0]!.source; }
async function bootstrap() { scenario = parseScenario(await readFile(defaultScenarioPath, 'utf8'), 'desktop'); await app.whenReady(); const clientRoot = app.isPackaged ? join(process.resourcesPath, 'desktop') : new URL('../../client/dist/desktop', import.meta.url).pathname;
protocol.handle('ambiental', async (request) => { const url = new URL(request.url); if (url.hostname === 'bundle') { const pathname = normalize(decodeURIComponent(url.pathname)).replace(/^[/\\]+/, '') || 'index.html'; if (pathname.includes('..')) return new Response('Forbidden', { status: 403 }); const path = join(clientRoot, pathname); try { const info = await stat(path); if (!info.isFile()) return new Response('Not found', { status: 404 }); return new Response(request.method === 'HEAD' ? null : createReadStream(path) as unknown as ReadableStream, { headers: { 'Content-Type': bundleMime(path), 'Content-Security-Policy': "default-src 'self'; script-src 'self'; style-src 'self'; font-src 'self'; img-src 'self' data:; media-src 'self' ambiental: blob: data:; connect-src 'self' ambiental:" } }); } catch { return new Response('Not found', { status: 404 }); } } if (url.hostname === 'media') { const granted = providers.get(url.pathname.slice(1)); if (!granted) return new Response('Not found', { status: 404 }); const info = await stat(granted.path); const range = request.headers.get('range'); if (range?.includes(',')) return new Response('Multiple ranges unsupported', { status: 416 }); let start = 0, end = info.size - 1; if (range) { const match = /^bytes=(\d*)-(\d*)$/.exec(range); if (!match) return new Response('Invalid range', { status: 416 }); if (match[1]) start = Number(match[1]); else if (match[2]) start = Math.max(0, info.size - Number(match[2])); if (match[2]) end = Number(match[2]); if (start > end || start >= info.size) return new Response('Range not satisfiable', { status: 416, headers: { 'Content-Range': `bytes */${info.size}` } }); end = Math.min(end, info.size - 1); } const length = end - start + 1; return new Response(request.method === 'HEAD' ? null : createReadStream(granted.path, { start, end }) as unknown as ReadableStream, { status: range ? 206 : 200, headers: { 'Content-Type': granted.mime, 'Access-Control-Allow-Origin': 'ambiental://bundle', 'Accept-Ranges': 'bytes', 'Content-Length': String(length), ...(range ? { 'Content-Range': `bytes ${start}-${end}/${info.size}` } : {}) } }); } return new Response('Not found', { status: 404 }); });
ipcMain.handle('ambiental:scenario', (event) => { assertTrustedSender(event); return scenario; });
ipcMain.handle('ambiental:choose', async (event, text: unknown) => { assertTrustedSender(event); if (typeof text !== 'string') throw new Error('Invalid scenario payload'); scenario = parseScenario(text, 'desktop'); rebuildTray(); return scenario; });
ipcMain.handle('ambiental:resolve', async (event, index: unknown) => { assertTrustedSender(event); if (typeof index !== 'number' || !Number.isInteger(index)) throw new Error('Invalid source index'); const all = [...scenario.bases.map((base) => base.source), ...scenario.jumpers.flatMap((jumper) => jumper.sources)]; const source = all[index]; if (!source) throw new Error('Unknown source index'); const result = await providers.resolve(source, process.cwd()); return { ...result, url: `ambiental://media/${result.token}` }; });
ipcMain.handle('ambiental:prepare-audio', async (event, source: unknown) => { assertTrustedSender(event); const result = await providers.resolve(validatedDesktopSource(source), process.cwd()); return { token: result.token, url: `ambiental://media/${result.token}`, durationSeconds: result.durationSeconds }; });
ipcMain.handle('ambiental:release-audio', async (event, token: unknown) => { assertTrustedSender(event); if (typeof token !== 'string') throw new Error('Invalid audio token'); await providers.revoke(token); });
ipcMain.handle('ambiental:embed-audio', async (event, source: unknown) => { assertTrustedSender(event); const extracted = await providers.extractWav(validatedDesktopSource(source), process.cwd()); if (extracted.bytes.byteLength > 16 * 1024 * 1024) throw new Error('Embedded source exceeds 16 MiB'); return { location: `data:audio/wav;base64,${Buffer.from(extracted.bytes).toString('base64')}`, durationSeconds: extracted.durationSeconds }; });
ipcMain.handle('ambiental:save-wav', async (event, source: unknown, suggestedName: unknown) => { assertTrustedSender(event); if (typeof suggestedName !== 'string') throw new Error('Invalid WAV name'); const response = await dialog.showSaveDialog(ensureWindow(), { defaultPath: `${safeName(suggestedName).replace(/\\.json$/, '')}.wav`, filters: [{ name: 'WAV audio', extensions: ['wav'] }] }); if (response.canceled || !response.filePath) return { canceled: true }; const result = await providers.saveWav(validatedDesktopSource(source), process.cwd(), response.filePath); return { canceled: false, ...result }; });
ipcMain.handle('ambiental:quit', (event) => { assertTrustedSender(event); quitting = true; app.quit(); });
ipcMain.handle('ambiental:choose-local-audio', async (event) => { assertTrustedSender(event); const response = await dialog.showOpenDialog(ensureWindow(), { properties: ['openFile'], filters: [{ name: 'Audio WAV/MP3', extensions: ['wav', 'mp3'] }] }); if (response.canceled || !response.filePaths[0]) return null; const path = await realpath(response.filePaths[0]); const info = await stat(path); if (!info.isFile() || !/\.(wav|mp3)$/i.test(path)) throw new Error('Choose a regular WAV or MP3 file'); return { path, name: basename(path) }; });
ipcMain.handle('ambiental:save-scenario', async (event, json: unknown, suggestedName: unknown, outputKinds: unknown) => { assertTrustedSender(event); if (typeof json !== 'string' || typeof suggestedName !== 'string') throw new Error('Invalid save payload'); if (Buffer.byteLength(json, 'utf8') > 90 * 1024 * 1024) throw new Error('Scenario exceeds 90 MiB'); parseScenario(json, 'desktop'); if (outputKinds !== undefined && (!Array.isArray(outputKinds) || outputKinds.some((kind) => kind !== 'embedded' && kind !== 'local-path' && kind !== 'youtube'))) throw new Error('Invalid materialization plan'); const response = await dialog.showSaveDialog(ensureWindow(), { defaultPath: safeName(suggestedName), filters: [{ name: 'Scenario JSON', extensions: ['json'] }] }); if (response.canceled || !response.filePath) return { canceled: true }; const document = JSON.parse(json) as { bases: Array<{ source: { location: string; clip?: { start_seconds: number; end_seconds: number }; volume?: unknown } }>; jumpers: Array<{ sources: Array<{ location: string; clip?: { start_seconds: number; end_seconds: number }; volume?: unknown }> }> }; const sources = [...document.bases.map((base) => base.source), ...document.jumpers.flatMap((jumper) => jumper.sources)]; const plan = outputKinds ?? sources.map((source) => source.location.startsWith('data:') ? 'embedded' : source.location.startsWith('https://') ? 'youtube' : 'local-path'); if (plan.length !== sources.length) throw new Error('Materialization plan does not match scenario sources'); const outputDirectory = join(response.filePath, '..'); for (let index = 0; index < sources.length; index += 1) { const source = sources[index]!; const kind = plan[index]!; windowRef?.webContents.send('ambiental:save-progress', { completed: index, total: sources.length, message: `Materializing source ${index + 1}` }); if (kind === 'youtube') { if (!source.location.startsWith('https://')) throw new Error('Only a YouTube input can be saved as a YouTube link'); continue; } const extracted = await providers.extractWav(source, outputDirectory); if (kind === 'embedded') { if (extracted.bytes.byteLength > 16 * 1024 * 1024) throw new Error('Embedded source exceeds 16 MiB after crop'); source.location = `data:audio/wav;base64,${Buffer.from(extracted.bytes).toString('base64')}`; } else { const path = join(outputDirectory, `${safeName(suggestedName).replace(/\.json$/, '')}-${index + 1}.wav`); await writeFile(path, extracted.bytes); source.location = basename(path); } delete source.clip; } const materialized = `${JSON.stringify(document, null, 2)}\n`; parseScenario(materialized, 'desktop'); windowRef?.webContents.send('ambiental:save-progress', { completed: sources.length, total: sources.length, message: 'Writing scenario JSON' }); await writeFile(response.filePath, materialized, 'utf8'); return { canceled: false, path: response.filePath }; });
ensureWindow(); rebuildTray(); app.on('activate', () => ensureWindow().show()); app.on('window-all-closed', () => {}); app.on('before-quit', () => providers.revokeAll()); }
void bootstrap();
